-- =============================================================================
-- Supabase SQL Setup for Annual General Meeting 2026 RSVP Table
-- (Includes deduplication by visitor_id to prevent multiple counts)
-- =============================================================================
-- Instructions:
-- 1. Open your Supabase Dashboard (https://supabase.com/dashboard)
-- 2. Select your project -> Go to "SQL Editor" in the left sidebar
-- 3. Click "New query", paste all contents below, and click "Run"
-- =============================================================================

-- 1. Create the rsvp_responses table (with unique visitor_id constraint)
CREATE TABLE IF NOT EXISTS rsvp_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visitor_id TEXT NOT NULL,
    event TEXT NOT NULL DEFAULT 'agm-2026',
    status TEXT NOT NULL CHECK (status IN ('accepted', 'declined', 'cancelled')),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_visitor_event UNIQUE (visitor_id, event)
);

-- 2. If the table already existed previously, safely migrate it:
DO $$ 
BEGIN 
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name='rsvp_responses' AND column_name='visitor_id'
    ) THEN
        ALTER TABLE rsvp_responses ADD COLUMN visitor_id TEXT DEFAULT 'legacy';
        ALTER TABLE rsvp_responses ALTER COLUMN visitor_id DROP DEFAULT;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name='rsvp_responses' AND column_name='updated_at'
    ) THEN
        ALTER TABLE rsvp_responses ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now());
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'unique_visitor_event'
    ) THEN
        -- Add unique constraint to deduplicate per visitor and event
        ALTER TABLE rsvp_responses ADD CONSTRAINT unique_visitor_event UNIQUE (visitor_id, event);
    END IF;

    -- Update status CHECK constraint to allow 'cancelled'
    ALTER TABLE rsvp_responses DROP CONSTRAINT IF EXISTS rsvp_responses_status_check;
    ALTER TABLE rsvp_responses ADD CONSTRAINT rsvp_responses_status_check CHECK (status IN ('accepted', 'declined', 'cancelled'));
END $$;

-- 3. Enable Row Level Security (RLS)
ALTER TABLE rsvp_responses ENABLE ROW LEVEL SECURITY;

-- 4. Policy: Allow visitors to insert their RSVP response
DROP POLICY IF EXISTS "Allow public to submit RSVP" ON rsvp_responses;
DROP POLICY IF EXISTS "Allow public to insert RSVP" ON rsvp_responses;
CREATE POLICY "Allow public to insert RSVP"
ON rsvp_responses
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

-- 5. Policy: Allow visitors to update their own RSVP response (Required for UPSERT deduplication & cancellation)
DROP POLICY IF EXISTS "Allow public to update RSVP" ON rsvp_responses;
CREATE POLICY "Allow public to update RSVP"
ON rsvp_responses
FOR UPDATE
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- 6. Policy: Allow reading for health checks, pings, and keep-alive workflows
DROP POLICY IF EXISTS "Allow public to read for ping" ON rsvp_responses;
CREATE POLICY "Allow public to read for ping"
ON rsvp_responses
FOR SELECT
TO anon, authenticated
USING (true);

-- =============================================================================
-- Quick Reference Queries for Supabase Dashboard SQL Editor:
-- =============================================================================
-- 1. Check total confirmed attendees:
--    SELECT count(*) AS confirmed_attendees FROM rsvp_responses WHERE event = 'agm-2026' AND status = 'accepted';
--
-- 2. View full breakdown by response status:
--    SELECT status, count(*) AS count FROM rsvp_responses WHERE event = 'agm-2026' GROUP BY status;
--
-- 3. View latest responses:
--    SELECT * FROM rsvp_responses ORDER BY updated_at DESC LIMIT 50;


